services:
  - type: web
    name: dr-kathe-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: BHASHINI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
    disk:
      name: outputs-data
      mountPath: /opt/render/project/src/outputs
      sizeGB: 1
